name: Build and Push Docker image

on:
  push:
    branches:
      - main   # roda sempre que fizer push na branch main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # permite publicar no GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/rotina-cura
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/rotina-cura
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
